version: "3.8"

services:
  
  eureka:
    build: ./service-registry-eureka/
    image: eureka-server:0.1
    container_name: eureka
    ports:
      - "8999:8999"

  db:
    image: postgres:14.4
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: organizer
    ports:
      - "5432:5432"
  
  auth:
    build: ./auth-service/
    image: auth-service:0.1
    container_name: auth
    ports:
      - "8998:8998"
    depends_on:
      - eureka
      - db


  
  
  api-gateway:
    build: ./api-gateway/
    image: api-gateway:0.1
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
  
